-- Create Database
CREATE OR REPLACE DATABASE DE_PROJECT1;

-- Create Schemas
CREATE OR REPLACE SCHEMA DE_PROJECT1.RAW;
CREATE OR REPLACE SCHEMA DE_PROJECT1.ANALYTICS;

-- Create Warehouse
CREATE OR REPLACE WAREHOUSE DE_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE DE_WH;
USE DATABASE DE_PROJECT1;
