-- Create Dimension Table (with Surrogate Key)

CREATE OR REPLACE TABLE ANALYTICS.DIM_PRODUCTS AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PRODUCT) AS PRODUCT_ID,
    PRODUCT
FROM (
    SELECT DISTINCT PRODUCT
    FROM RAW.SALES
);
