-- Create Fact Table (using PRODUCT_ID)

CREATE OR REPLACE TABLE ANALYTICS.FACT_SALES AS
SELECT
    S.ORDER_ID,
    S.ORDER_DATE,
    S.CUSTOMER_ID,
    D.PRODUCT_ID,
    S.QUANTITY,
    S.UNIT_PRICE,
    S.QUANTITY * S.UNIT_PRICE AS TOTAL_AMOUNT
FROM RAW.SALES S
JOIN ANALYTICS.DIM_PRODUCTS D
    ON S.PRODUCT = D.PRODUCT;
