-- Monthly Revenue by Product

SELECT
    DATE_TRUNC('MONTH', f.ORDER_DATE) AS MONTH,
    d.PRODUCT,
    SUM(f.QUANTITY) AS TOTAL_QTY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ANALYTICS.FACT_SALES f
JOIN ANALYTICS.DIM_PRODUCTS d
    ON f.PRODUCT_ID = d.PRODUCT_ID
GROUP BY 1,2
ORDER BY 1,2;

-- Total Revenue

SELECT
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ANALYTICS.FACT_SALES;
